version: "2"
services:
  api:
    build: .
    ports:
      - "3000:3005"
    restart: always
    depends_on:
      - mongo
    environment:
      WAIT_HOSTS: mongo:27017
    env_file: .env.docker
  mongo:
    image: mongo:4.0.4
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    env_file: .env.docker